apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: default
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'kubernetes-nodes'
        static_configs:
          # 10.42.0.1 is the default host gateway IP address inside K3s
          - targets: ['10.42.0.1:9100'] 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring
  template:
    metadata:
      labels:
        app: monitoring
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:v2.45.0
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus/prometheus.yml
          subPath: prometheus.yml
        resources:
          limits:
            memory: "250Mi"
      - name: grafana
        image: grafana/grafana-oss:10.0.0
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "250Mi"
      volumes:
      - name: config-volume
        configMap:
          name: prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-service
spec:
  type: NodePort
  selector:
    app: monitoring
  ports:
    - name: prometheus
      port: 9090
      targetPort: 9090
    - name: grafana
      port: 3000
      targetPort: 3000
      nodePort: 32000
